# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "80:80"
    environment:
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
